#pragma once
#define SECRET_SSID "NOME_DA_REDE_2G4"
#define SECRET_OPTIONAL_PASS "SENHA_DA_REDE"
#define SECRET_DEVICE_LOGIN_NAME "DEVICE_LOGIN_NAME_OU_DEVICE_ID"
#define SECRET_DEVICE_KEY "SECRET_DEVICE_KEY"
